version: '3.9'

services:
  mysqldb:
    image: mysql:8.0.33
    container_name: medcloudChallenge-mysql
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
      - MYSQL_DATABASE=$DB_NAME
      - MYSQL_TCP_PORT=$MYSQL_DOCKER_PORT
    ports:
      - $MYSQL_LOCAL_PORT:$MYSQL_DOCKER_PORT
    expose:
      - $MYSQL_DOCKER_PORT
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      timeout: 5s
      retries: 10

    volumes:
      - /var/lib/mysql
  app:
    depends_on:
      mysqldb:
        condition: service_healthy
    build:
      context: ./
      dockerfile: Dockerfile
    working_dir: /usr/src/medcloudChallenge
    container_name: medcloudChallenge-api
    restart: unless-stopped
    env_file: ./.env
    environment:
      - DB_USERNAME=$DB_USERNAME
      - DB_PASSWORD=$DB_PASSWORD
      - DB_NAME=$DB_NAME
      - DB_HOST=mysqldb
      - DB_DIALECT=$DB_DIALECT
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    stdin_open: true
    tty: true
